name: Go Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Windows exe
        run: |
          mkdir -p build
          GOOS=windows GOARCH=amd64 go build -o build/GOFK-GUET-WiFI.exe ./cmd/main

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/GOFK-GUET-WiFI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
